version: '3.3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
  php-fpm:
    image: nawawishkid/wpth:php7.2-fpm
    # domainname: example.local
    # extra_hosts:
    #   - "example 127.0.0.1"
    volumes:
      - ./www:/var/www
    expose:
      - "9000"
    depends_on:
      - mysql
  apache:
    image: nawawishkid/wpth:apache-latest
    volumes:
      - ./www:/var/www
      - ./services/apache/sites-available:/etc/apache2/sites-available
    ports:
      - "8888:80"
  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./services/nginx/sites-available
    