version: '3.3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
  php-fpm:
    image: nawawishkid/wpth:php7.2-fpm
    volumes:
      - ./www:/var/www
  apache:
    image: nawawishkid/wpth:apache-latest
    volumes:
      - ./www:/var/www
      - ./config/apache/sites-available
  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./config/nginx/sites-available
    