version: "3.3"

services:
  nginx:
    image: nginx:latest
    depends_on: apache
    ports:
      - "8010:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
      - ./docker/nginx/sites-available:/etc/nginx/sites-available
  apache:
    image: nawawishkid/apache2:latest
    depends_on: php-fpm
    ports:
      - "8011:80"
    volumes:
      - ./docker/apache2/apache2.conf/:/etc/apache2/apache2.conf
      - ./docker/apache2/sites-available:/etc/apache2/sites-available
      - ./www:/var/www
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD: mysql@wpthai.io
  php-fpm:
    image: php:7-fpm
    depends_on: mysql
    volumes:
      - ./www:/var/www

  # wp-cli:
  #   image: wordpress:cli
  #   depends_on: php