version: '3.3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
  php-fpm:
    image: nawawishkid/wpth:php7.2-fpm
    volumes:
      - /var/www/portfolio/wordpress/wpthai.io/www:/var/www
    depends_on:
      - mysql
  apache:
    image: nawawishkid/wpth:apache-latest
    volumes:
      - /var/www/portfolio/wordpress/wpthai.io/www:/var/www
      - /var/www/portfolio/wordpress/wpthai.io/conf/apache/sites-available
    ports:
      - "80:80"
  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - /var/www/portfolio/wordpress/wpthai.io/conf/nginx/sites-available
    